print("ERIKJIMENEZ")
print("..........")
print("ex2.1")
print("1", "2", "3", "5", "++", sep="---", end="\n")
print("..........")
print("ex2.2")
print("Estoy")
print("'Algunos símbolos'")
print("'Son difíciles de imprimir:'/")
print("I'm a programmer!!")
print(".......")
print("Ex2.3")
print("I'm Monty Python.")
print(".............")
print("ex2.4")
x = ((3+2) / (2*5)) **2
print (x)